export const ENV_VARIABLES = {
  GOOGLE_CLIENT_ID: `${import.meta.env.VITE_GOOGLE_CLIENT_ID}`,
  GOOGLE_CLIENT_SECRET: `${import.meta.env.VITE_GOOGLE_CLIENT_SECRET}`,
  MAPBOX_ACCESS_TOKEN: `${import.meta.env.VITE_MAPBOX_ACCESS_TOKEN}`,
  FILESTACK_API_KEY: `${import.meta.env.VITE_FILESTACK_API_KEY}`,
  OPENROUTESERVICE_API_KEY: `${import.meta.env.VITE_OPENROUTESERVICE_API_KEY}`,
  GOOGLE_AUTH_SERVER_URL: `${import.meta.env.VITE_GOOGLE_AUTH_SERVER_URL}`,
  GOOGLE_AUTH_LOG_OUT_URL: `${import.meta.env.VITE_GOOGLE_AUTH_LOG_OUT_URL}`,
  BASE_URL: `${import.meta.env.VITE_BASE_URL}`,
  OPEN_ROUTE_URL: `${import.meta.env.VITE_OPEN_ROUTE_URL}`,
  OPEN_ROUTE_POIS_URL: `${import.meta.env.VITE_OPEN_ROUTE_POIS_URL}`,
  TOKEN_REFRESH_URL: `${import.meta.env.VITE_TOKEN_REFRESH_URL}`,
};
